[package]
name = "Mandelbrot"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
termion = "1.5.6"
#rug = "1.16"
#decimal = "2.1.0"
rust_decimal = "1.23"
rust_decimal_macros = "1.23"